spring.application.name=devops-03-backend
server.port=8080
server.servlet.context-path=/api
spring.data.mongodb.uri=mongodb://localhost:27017/campus_food
spring.data.mongodb.auto-index-creation=true

# Swagger/OpenAPI (option)
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.use-root-path=true

# JWT secret key
jwt.secret=iyvJXYbbaEjkkX+D2aTOLW7AJzH+rhMa/W7b3Q/6KEUMd/v6zDLebp6LYm13O3nPORpdQZsvL5GxwnyOWBUM+w==

# File Upload Settings
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
file.upload-dir=uploads/images